version: "3.9"

services:
    web:
      build: .
      # command: python /bookstore_Inc2/manage.py runserver 0.0.0.0:8000
      command: gunicorn bookstoreProject.wsgi -b 0.0.0.0:8000
      volumes:
        - .:/bookstore_Inc2
      ports:
        - 8000:8000
      depends_on:
        - db
      environment:
        - "DJANGO_SECRET_KEY=django-insecure-ixs1h-h8!bl_e^cleo&8g7hlu+5b0y5#x!9+*gi&&&m)cs6i+_"
        - "DJANGO_DEBUG=True"
        - "DJANGO_SECURE_SSL_REDIRECT=False"
        - "DJANGO_SECURE_HSTS_SECONDS=0"
        - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
        - "DJANGO_SECURE_HSTS_PRELOAD=False"
        - "DJANGO_SESSION_COOKIE_SECURE=False"
        - "DJANGO_CSRF_COOKIE_SECURE=False"
    db:
      image: postgres:13
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: